
path=(
  /usr/local/{bin,sbin}
  $HOME/.bin
  $HOME/.local/bin
  $path
)

source ~/.dotfiles/config/zsh/git-functions.zsh
source ~/.dotfiles/config/zsh/functions.zsh 

# ENV
export GOPATH=$HOME/.go
export EDITOR='/usr/bin/nvim'
export VISUAL='/usr/bin/nvim'
export FZF_DEFAULT_OPTS='--preview-window border-sharp -i --height=50%'

#Config Files
alias dots="cd ~/.dotfiles"
alias zrc="nvim ~/.zprofile && source ~/.zshrc"
alias arc="cd ~/.config/awesome && nvim rc.lua"

# Quick Shortcuts
alias q="exit"
alias myip="curl https://echoip.xyz"
alias grep="rg"
alias grepl="rg | less -R"
alias q="exit"

# PARU 
alias update="paru -Syu --removemake  --sudoloop"
alias install="paru -Slq | fzf --multi --preview 'paru -Si {1}' | xargs -ro paru -S --removemake --sudoloop"
alias remove="paru -Qq | fzf --multi --preview 'paru -Qi {1}' | xargs -ro paru -Rcns"
alias cclean="sudo paccache -rk3 && sudo pacman -Sc --noconfirm"
alias pclean="paru -Qdtq | xargs -ro paru -Rs"

# LS
TREE_IGNORE="cache|log|logs|node_modules|vendor"
alias ls='exa --group-directories-first'
alias la='ls -a'
alias ll='ls --git -la'
alias lt='ls --tree -D -L 2 -I ${TREE_IGNORE}'
alias ltt='ls --tree -D -L 3 -I ${TREE_IGNORE}'
alias lttt='ls --tree -D -L 4 -I ${TREE_IGNORE}'
alias ltttt='ls --tree -D -L 5 -I ${TREE_IGNORE}'

# FZF File explorer
function  exp() {
  source ~/.dotfiles/scripts/explorer.sh
}

zle -N exp
bindkey -s '^o' 'exp\n'
