
path=(
  /usr/local/{bin,sbin}
  $HOME/.bin
  $HOME/.local/bin
  $path
)

eval "$(jump shell)"

source ~/.dotfiles/config/zsh/functions.zsh 
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

# ENV
export GOPATH=$HOME/.go
export EDITOR='/usr/bin/nvim'
export VISUAL='/usr/bin/nvim'

# FZF
export FZF_DEFAULT_OPTS='--preview-window border-sharp -i --height=50%'
export FZF_TMUX=1


# NNN
export NNN_PLUG='p:preview-tui;i:imgview;j:autojump;v:rsynccp'
export NNN_FIFO=/tmp/nnn.fifo
export NNN_FCOLORS='0000d6000000000000000000'

#Config Files
alias dots="cd ~/.dotfiles"
alias zrc="nvim ~/.zprofile && source ~/.zshrc"
alias arc="cd ~/.config/awesome && nvim rc.lua"

# Quick Shortcuts
alias n="nnn -e"
alias zsrc="source ~/.zprofile"
alias q="exit"
alias grep="rg"
alias grepl="rg | less -R"
alias q="exit"

# PARU 
alias update="paru -Syu --removemake  --sudoloop"
alias install="paru -Slq | fzf --multi --preview 'paru -Si {1}' | xargs -ro paru -S --removemake --sudoloop"
alias remove="paru -Qq | fzf --multi --preview 'paru -Qi {1}' | xargs -ro paru -Rcns"
alias cclean="sudo paccache -rk3 && sudo pacman -Sc --noconfirm"
alias pclean="paru -Qdtq | xargs -ro paru -Rs"

# LS
TREE_IGNORE="cache|log|logs|node_modules|vendor"
alias ls='exa --group-directories-first'
alias la='ls -a'
alias ll='ls --git -la'
alias lt='ls --tree -D -L 2 -I ${TREE_IGNORE}'
alias ltt='ls --tree -D -L 3 -I ${TREE_IGNORE}'
alias lttt='ls --tree -D -L 4 -I ${TREE_IGNORE}'
alias ltttt='ls --tree -D -L 5 -I ${TREE_IGNORE}'
